import{a as d,S as y,i as a}from"./assets/vendor-frHSA4Lh.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const g="https://pixabay.com/api/",h="50784112-005c51f7743801558c0ea8079";async function b(s){const o=encodeURIComponent(s);try{return(await d.get(g,{params:{key:h,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}catch(t){throw console.error("Помилка під час отримання зображень:",t),t}}const l=document.querySelector(".js-gallery"),f=document.querySelector(".js-loader");let c=new y(".gallery a",{captionsData:"alt",captionDelay:250});function L(s){if(!Array.isArray(s)||s.length===0){l.innerHTML="",c.refresh();return}const o=s.map(({webformatURL:t,largeImageURL:n,tags:e,likes:r,views:i,comments:p,downloads:m})=>`<li class="gallery-item">
          <a class="gallery-link" href="${n}">
            <img class="gallery-image" src="${t}" alt="${e}" />
          </a>
          <div class="info">
            <p class="info-item"><b>Likes</b> ${r}</p>
            <p class="info-item"><b>Views</b> ${i}</p>
            <p class="info-item"><b>Comments</b> ${p}</p>
            <p class="info-item"><b>Downloads</b> ${m}</p>
          </div>
        </li>`).join("");l.innerHTML=o,c.refresh()}function v(){l.innerHTML="",c.refresh()}function P(){f.classList.add("is-visible")}function A(){f.classList.remove("is-visible")}const E=document.querySelector(".js-form"),u=document.querySelector('input[name="search-text"]');E.addEventListener("submit",async s=>{s.preventDefault();const o=u.value.trim();if(o===""){a.error({title:"Error",message:"Будь ласка, введіть щось для пошуку!",position:"topRight"});return}v(),P();try{const t=await b(o);t.hits.length===0?a.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#ef4040",messageColor:"#fff",titleColor:"#fff"}):L(t.hits)}catch(t){a.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight"}),console.error("Помилка під час пошуку зображень:",t)}finally{A(),u.value=""}});
//# sourceMappingURL=index.js.map
